# Generated by Django 2.2.4 on 2021-02-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('partyType', models.CharField(choices=[('C', 'Customer'), ('S', 'Supplier')], default='C', max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('sellingPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(max_length=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.PositiveIntegerField()),
                ('billedBy', models.CharField(max_length=25)),
                ('billTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('billedDateTime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suppliers', to='POS.Party')),
            ],
        ),
        migrations.CreateModel(
            name='SalesMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.PositiveIntegerField()),
                ('billedBy', models.CharField(max_length=25)),
                ('billTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('billedDateTime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='POS.Party')),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='Unnammed', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('mainBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salesbills', to='POS.SalesMain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salesproducts', to='POS.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('mainBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseBills', to='POS.PurchaseMain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseProducts', to='POS.Product')),
            ],
        ),
    ]
